---
- name: smoke test
  hosts: localhost
  connection: local
  gather_facts: false
  roles:
    - osp-facts

- name: testing frontend
  hosts: frontend
  gather_facts: false
  tasks:
    - name: Curl website
      uri:
        url: "http://{{ ansible_default_ipv4.address }}/ping"
        return_content: yes
        status_code: 200
      register: webpage
      delegate_to: localhost

    - name: Fail if 'Ansible has done its job' is not in the page content
      fail:
      when: "'Ansible has done its job' not in webpage.results[0].content"
      tags:
        - osp.smoke
