---
- name: smoke test
  hosts: localhost
  connection: local
  gather_facts: false
  roles:
    - osp-facts

- name: testing frontend
  hosts: frontend
  gather_facts: true
  tasks:
    - name: Curl website
      uri:
        url: "http://{{ ansible_host }}"
        return_content: yes
        status_code: 200
      register: webpage
      delegate_to: localhost

    - name: Fail if 'Ansible' is not in the page content
      fail:
      when: "'Ansible' not in webpage.content"
      tags:
        - osp.smoke
