---
- name: smoke test
  hosts: workstation
  gather_facts: false
  tasks:
    - name: OpenStack servers
      os_server_info:
        cloud: openstack
        region_name: regionOne
      register: r_os_servers
    
    - name: Add host
      add_host:
       hostname: "{{ item.name }}"
       ansible_host: "{{ item.public_v4 }}"
       group: "{{ item.metadata.group }}"
       ansible_ssh_private_key_file: ~/.ssh/openstack.pem
       ansible_ssh_user: cloud-user
      loop: "{{ r_os_servers.openstack_servers }}"
    
    - name: Add host
      add_host:
       hostname: "{{ item.name }}"
       ansible_host: "{{ item.public_v4 }}"
       group: "{{ item.metadata.deployment_name }}"
       ansible_ssh_private_key_file: ~/.ssh/openstack.pem
       ansible_ssh_user: cloud-user
      loop: "{{ r_os_servers.openstack_servers }}"

    - name: Curl website
      uri:
        url: "http://frontend/ping"
        return_content: yes
        status_code: 200
      register: webpage
      delegate_to: localhost

    - name: Fail if 'Ansible has done its job' is not in the page content
      fail:
      when: "'Ansible has done its job' not in webpage.results[0].content"
      tags:
        - osp.smoke
